apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-shell
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: debug-shell
      app.kubernetes.io/instance: debug-shell
      app.kubernetes.io/version: {{ .Values.image.tag }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: debug-shell
        app.kubernetes.io/instance: debug-shell
        app.kubernetes.io/version: {{ .Values.image.tag }}
    spec:
      containers:
        - name: debug-shell
          image: localhost:5000/debug-shell:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
