apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# You can add common labels, annotations, or other customization here if needed
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: debug-shell
    app.kubernetes.io/instance: debug-shell
