# Source: debug-shell/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: debug-shell
  labels:
    app.kubernetes.io/name: debug-shell
    app.kubernetes.io/instance: debug-shell
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: debug-shell
    app.kubernetes.io/instance: debug-shell
