apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-shell
  labels:
    app: debug-shell
spec:
  selector:
    matchLabels:
      app: debug-shell
  replicas: 1
  template:
    metadata:
      labels:
        app: debug-shell
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
      # hostNetwork: true
      dnsPolicy: Default
