apiVersion: v1
kind: Pod
metadata:
  name: debug-shell
  labels:
    app: debug-shell
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx
      # ports:
      # - containerPort: 62000
      # name: http
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
  # hostNetwork: true
  dnsPolicy: Default
